/**
 * Bundle the Vercel function into a single self-contained `api/index.js`.
 *
 * WHY THIS EXISTS
 * ---------------
 * Vercel transpiles `api/*.ts` but does not bundle it: relative imports survive
 * into the lambda as runtime module paths, and `server/` is not shipped
 * alongside. Both spellings failed in production while the build reported READY —
 * first `/var/task/server/app.ts`, then `/var/task/server/app`. Rather than keep
 * guessing at the platform's module resolution, the function arrives as one file
 * with nothing left to resolve but Node builtins.
 *
 * The output is committed, so what deploys is exactly what was reviewed, and
 * `scripts/check.sh` fails if it has drifted from its source.
 */
import { build } from 'esbuild';

const result = await build({
  entryPoints: ['server/vercel-entry.ts'],
  outfile: 'api/index.js',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  minify: false, // a reviewable diff matters more here than a few kilobytes
  banner: {
    js: '// GENERATED by scripts/build-api.mjs from server/vercel-entry.ts — do not edit.',
  },
  logLevel: 'warning',
});
if (result.errors.length) process.exit(1);
console.log('api/index.js bundled from server/vercel-entry.ts');
